### ISSUE TITLE
Cannot read property 'bar' of undefined

### ISSUE THREAD

**Issue by shrpv** [pzs/vuetify-toast#10]
After my update vuetify snackbar stopped showing with error:

Error in render: "TypeError: Cannot read property 'bar' of undefined"

found in

---> <VSnackbar>

Can you fix it? Thanks you!

**Comment by shrpv** [comment]
https://www.npmjs.com/package/vuetify-toast-snackbar-ng

**Comment by dunksmith** [comment]
I get the same issue with the latest version of this package:

_> Error in render: "TypeError: Cannot read property 'bar' of undefined"_

Seems to be caused by `this.$vuetify.application` being undefined.

The previous comment links to a different "toast" npm package, which does indeed work, but I prefer the API of this one - any idea why it is broken?
